version: "3.8"

services:
  fastapi_app:
    build: .
    container_name: fastapi_container
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    restart: always
    env_file:
      - .env
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

